<a href="https://colab.research.google.com/github/Digvijay25/PyTorch-Deep-Learning-Bootcamp/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
torch.__version__

'2.6.0+cu124'

In [12]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [13]:
scaler.ndim

0

In [14]:
scaler.item()

7

In [15]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [18]:
MATRIX = torch.tensor([[7, 8,],
                        [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [20]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [21]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [22]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.3346, 0.6539, 0.6744, 0.1041],
        [0.7017, 0.3679, 0.0728, 0.5188],
        [0.3904, 0.1542, 0.9971, 0.9252]])

In [23]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [24]:
random_image_size_tensor.size()

torch.Size([224, 224, 3])

In [25]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros.dtype

torch.float32

In [27]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [28]:
ones.shape, ones.ndim

(torch.Size([3, 4]), 2)

In [29]:
zero_to_ten =  torch.arange(0, 10)
zero_to_ten.shape, zero_to_ten.ndim

(torch.Size([10]), 1)

In [30]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
float_32_tensor = torch.tensor([7.0, 8.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [32]:
float_16_tensor = torch.tensor([7.0, 8.0, 9.0],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [33]:
some_tensor = torch.rand(3, 5)

print(some_tensor)
print(some_tensor.shape)
print(some_tensor.ndim)
print(some_tensor.device)

tensor([[1.0000, 0.8749, 0.6808, 0.8552, 0.7925],
        [0.9749, 0.1437, 0.5514, 0.8563, 0.2850],
        [0.9744, 0.6770, 0.9732, 0.5264, 0.2924]])
torch.Size([3, 5])
2
cpu


In [34]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [37]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [38]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [41]:
tensor * tensor

tensor([1, 4, 9])

In [42]:
torch.matmul(tensor, tensor)

tensor(14)

In [43]:
tensor @ tensor

tensor(14)

In [44]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [45]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [46]:
torch.mm(tensor, tensor.T)

<ipython-input-46-e91e0661583d>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3725.)
  torch.mm(tensor, tensor.T)


RuntimeError: self must be a matrix

In [49]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [50]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=8) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,  0.6104],
        [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,  1.0926],
        [ 6.7696,  3.1736, -0.2486,  0.9506, -0.3216,  3.7842,  2.8995,  1.5748]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 8])


In [51]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.min(), x.max()

(tensor(0), tensor(90))

In [53]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [54]:
x.type(torch.float32).mean()

tensor(45.)

In [55]:
x.sum()

tensor(450)

In [56]:
x.dtype

torch.int64

In [57]:
x.type(torch.float32).dtype

torch.float32

In [58]:
tensor.argmax()

tensor(2)

In [59]:
tensor

tensor([1, 2, 3])

In [60]:
x.argmax()

tensor(9)

In [61]:
tensor = torch.arange(0., 100., 10.)
tensor.dtype

torch.float32

In [62]:
tensor.type(torch.float16)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [63]:
tensor.type(torch.int8)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [64]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [65]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [66]:
x.shape

torch.Size([7])

In [67]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [68]:
z = x.view(1, 7)
z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [69]:
z.shape

torch.Size([1, 7])

In [70]:
z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [71]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [72]:
x_stacked = torch.stack([x, x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [73]:
x_stacked = torch.stack([x, x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.]])

In [74]:
x, x.shape

(tensor([5., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [75]:
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [76]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7.])

In [77]:
x_reshaped.squeeze().shape

torch.Size([7])

In [78]:
x_reshaped.squeeze().unsqueeze(dim=0).shape

torch.Size([1, 7])

In [79]:
x_reshaped.squeeze().unsqueeze(dim=1).shape

torch.Size([7, 1])

In [80]:
x_original = torch.rand(224, 224, 3)
x_original.shape

torch.Size([224, 224, 3])

In [81]:
x_permuted = torch.permute(x_original, (2, 0, 1))
x_permuted.shape

torch.Size([3, 224, 224])

In [82]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x.shape

torch.Size([1, 3, 3])

In [83]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [84]:
x[0][0]

tensor([1, 2, 3])

In [85]:
x[0][0][0]

tensor(1)

In [86]:
x[:, 0]

tensor([[1, 2, 3]])

In [87]:
x[:, 1]

tensor([[4, 5, 6]])

In [88]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [89]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [90]:
x[0, 0, :]

tensor([1, 2, 3])

In [91]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [92]:
torch.from_numpy(array)

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [93]:
torch.random.manual_seed(42)

In [94]:
!nvidia-smi

Fri Apr 11 05:28:56 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   47C    P0             26W /   70W |     104MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [95]:
import torch
torch.cuda.is_available()

True

In [96]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [97]:
torch.cuda.device_count()

1

In [98]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [99]:
tensor.device

device(type='cpu')

In [100]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [101]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])